/** Chuỗi giao diện tiếng Việt (UTF-8). */

export const NAV = {
  OPEN_MENU: 'Mở menu',
  CLOSE_MENU: 'Đóng menu',
  HOME: 'Trang chủ',
  ABOUT: 'Giới thiệu',
  COURSES: 'Khóa học',
  CLASSES: 'Lớp học',
  TEAM: 'Đội ngũ',
  TESTIMONIALS: 'Đánh giá',
  CONTACT: 'Liên hệ',
  DASHBOARD: 'Bảng điều khiển',
  SIGN_OUT: 'Đăng xuất',
  SIGN_IN: 'Đăng nhập',
  THEME_DARK: 'Chuyển sang giao diện tối',
  THEME_LIGHT: 'Chuyển sang giao diện sáng',
};

/** Địa chỉ / SĐT / email hiển thị trên trang Liên hệ và footer. */
export const SITE_CONTACT = {
  ADDRESS: '182 Lương Thế Vinh',
  PHONE: '0986551191',
  EMAIL: 'buiquang1901@gmail.com',
};

export const FOOTER = {
  QUICK_LINKS: 'Liên kết nhanh',
  PRIVACY: 'Chính sách bảo mật',
  TERMS: 'Điều khoản sử dụng',
  CONTACT_TITLE: 'Liên hệ',
  ADDRESS: SITE_CONTACT.ADDRESS,
  SHARE: 'Chia sẻ',
  COMMUNITY: 'Cộng đồng',
  VIDEO: 'Video',
  LINK: 'Liên kết',
  NEWSLETTER: 'Bản tin',
  NEWSLETTER_DESC:
    'Đăng ký để nhận tin khóa học và cập nhật mới.',
  EMAIL_PLACEHOLDER: 'Email của bạn',
  SUBSCRIBE: 'Đăng ký',
  COPYRIGHT: 'Bảo lưu mọi quyền.',
};

export const PAGE = {
  HOME_CRUMB: 'Trang chủ',
};

export const LAYOUT = {
  BACK_TO_TOP: 'Lên đầu trang',
};

export const ROLE = {
  NO_PROFILE:
    'Tài khoản chưa có hồ sơ. Hãy đăng xuất và đăng nhập lại, hoặc liên hệ hỗ trợ.',
};

export const ERR = {
  LOAD: 'Không tải được dữ liệu',
  LOAD_ENROLLMENTS: 'Không tải được đăng ký khóa học',
  LOAD_TEAM: 'Không tải được đội ngũ',
  LOAD_TESTIMONIALS: 'Không tải được đánh giá',
  LOAD_FAILED: 'Tải thất bại',
  NOT_FOUND: 'Không tìm thấy',
  LOGIN_FAILED: 'Đăng nhập thất bại',
  PROFILE_NOT_LOADED:
    'Không tải được hồ sơ người dùng. Vui lòng thử lại hoặc liên hệ hỗ trợ.',
  SIGNUP_FAILED: 'Đăng ký thất bại',
  SEND_FAILED: 'Gửi thất bại',
  ENROLL_FAILED: 'Đăng ký khóa học thất bại',
  ENROLL_CLASS_FAILED: 'Tham gia lớp thất bại',
  LOAD_ENROLL_REPORT: 'Không tải báo cáo đăng ký',
  LOAD_QUIZ_ATTEMPTS: 'Không tải kết quả bài kiểm tra',
  LOAD_QUIZ_ANALYTICS: 'Không tải thống kê bài kiểm tra',
  INVALID_JSON: 'JSON không hợp lệ',
};

export const COMMON = {
  LOADING: 'Đang tải…',
  PLEASE_WAIT: 'Vui lòng chờ…',
  EMAIL: 'Email',
  PASSWORD: 'Mật khẩu',
  DELETE: 'Xóa',
  ADD: 'Thêm',
  SAVE: 'Lưu',
  CANCEL: 'Hủy',
  VIEW: 'Xem',
  OPEN: 'Mở',
  YES: 'Có',
  NO: 'Không',
  FREE: 'Miễn phí',
  FEE_LABEL: 'Học phí',
  ALL_LEVELS: 'Mọi cấp độ',
  HOURS: 'giờ',
  DASH_CRUMB: 'Bảng điều khiển',
};

export const HOME = {
  SLIDE1_KICKER: 'Nền tảng học trực tuyến hàng đầu',
  SLIDE1_TITLE:
    'Học kỹ năng sẵn sàng việc làm từ khóa học trực tuyến có chứng chỉ',
  SLIDE1_TEXT:
    'Khám phá khóa học công nghệ, kinh doanh, nghệ thuật và hơn thế nữa. Bắt đầu học ngay!',
  READ_MORE: 'Đọc thêm',
  JOIN_NOW: 'Tham gia ngay',
  SLIDE2_KICKER: 'Chào mừng đến EduStart',
  SLIDE2_TITLE: 'Rèn luyện kỹ năng theo nhịp của bạn',
  SLIDE2_TEXT: 'Nội dung chất lượng, giảng viên chuyên gia và cộng đồng hỗ trợ.',
  BROWSE_COURSES: 'Xem khóa học',
  BROWSE_CLASSES: 'Xem lớp học',
  PREV_SLIDE: 'Slide trước',
  NEXT_SLIDE: 'Slide sau',
  GO_SLIDE: (n) => `Đến slide ${n}`,
  SECTION_COURSES: 'Khóa học',
  POPULAR_COURSES: 'Khóa học phổ biến',
  VIEW_ALL_COURSES: 'Xem tất cả khóa học',
  VIEW_ALL_TEAM: 'Xem đầy đủ đội ngũ',
  INSTRUCTOR_TITLE: 'Trở thành giảng viên',
  INSTRUCTOR_TEXT:
    'Giảng viên trên khắp thế giới đang dạy hàng triệu học viên. Chúng tôi cung cấp công cụ và kỹ năng để bạn dạy những gì mình yêu thích.',
  START_TEACHING: 'Bắt đầu giảng dạy',

  FEATURES_TITLE: 'Phát triển mục tiêu học tập cùng EduStart',
  FEATURES_SUB:
    'Nền tảng tập trung vào chất lượng, linh hoạt và giá trị thực cho người học.',
  FEATURE1_TITLE: 'Học đa lĩnh vực',
  FEATURE1_TEXT:
    'Danh mục khóa học phong phú từ công nghệ đến kỹ năng mềm, phù hợp nhiều đối tượng và mục tiêu nghề nghiệp.',
  FEATURE2_TITLE: 'Tiết kiệm chi phí',
  FEATURE2_TEXT:
    'Học trực tuyến giúp tối ưu ngân sách, không chi phí di chuyển và linh hoạt theo thời gian cá nhân.',
  FEATURE3_TITLE: 'Học tập linh hoạt',
  FEATURE3_TEXT:
    'Truy cập nội dung mọi lúc, tự chọn nhịp học và ôn luyện phù hợp lịch trình của bạn.',
  FEATURE4_TITLE: 'Chứng chỉ giá trị',
  FEATURE4_TEXT:
    'Hoàn thành khóa học với chứng nhận ghi nhận kỹ năng, hỗ trợ hồ sơ và phát triển sự nghiệp.',

  ABOUT_SECTION_KICKER: 'Giới thiệu',
  ABOUT_SECTION_H2: 'Giới thiệu về EduStart',
  ABOUT_SECTION_P:
    'EduStart là nền tảng học trực tuyến hướng đến trải nghiệm dễ tiếp cận, nội dung cập nhật và cộng đồng học viên tích cực.',
  ABOUT_SECTION_BULLETS: [
    'Nội dung được xây dựng bài bản, sát thực tế',
    'Đội ngũ giảng viên và chuyên gia',
    'Học mọi lúc, mọi nơi trên thiết bị kết nối mạng',
    'Theo dõi tiến độ và hỗ trợ người học',
    'Cộng đồng chia sẻ và trao đổi',
    'Cập nhật khóa học và tính năng thường xuyên',
  ],
  LEARN_MORE: 'Tìm hiểu thêm',

  PROGRAMS_CTA_H2: 'Khám phá chương trình đào tạo',
  PROGRAMS_CTA_SUB:
    'Đăng ký để truy cập hàng trăm bài giảng, bài tập và lộ trình rõ ràng theo từng chủ đề.',
  REGISTER_NOW: 'Đăng ký ngay',

  MAJORS_KICKER: 'Chuyên ngành',
  MAJORS_H2: 'Chủ đề đào tạo nổi bật',

  FEATURED_PROGRAMS_KICKER: 'Khóa học',
  FEATURED_PROGRAMS_H2: 'Khám phá các chương trình đào tạo nổi bật',

  FEATURED_CLASSES_KICKER: 'Lớp học',
  FEATURED_CLASSES_H2: 'Lớp học trực tiếp đang mở',
  VIEW_ALL_CLASSES: 'Xem tất cả lớp',

  FAQ_TITLE: 'Câu hỏi thường gặp',
  FAQ_ITEMS: [
    {
      q: 'EduStart có những loại khóa học nào?',
      a: 'Chúng tôi cung cấp khóa học trực tuyến đa lĩnh vực: công nghệ, kinh doanh, kỹ năng mềm và hơn thế nữa. Bạn có thể duyệt theo danh mục trên trang Khóa học.',
    },
    {
      q: 'Tôi có thể học theo lịch riêng không?',
      a: 'Có. Nội dung được thiết kế để bạn tự học theo nhịp cá nhân, truy cập lôi lại bài giảng bất cứ khi nào.',
    },
    {
      q: 'Sau khi học xong có được chứng nhận không?',
      a: 'Tùy khóa học, hệ thống ghi nhận hoàn thành và có thể cấp chứng nhận hoặc huy hiệu điểm danh theo chính sách từng chương trình.',
    },
    {
      q: 'Làm sao để liên hệ hỗ trợ?',
      a: 'Bạn có thể gửi tin nhắn qua trang Liên hệ hoặc email hiển thị ở chân trang. Đội ngũ sẽ phản hồi trong thời gian làm việc.',
    },
    {
      q: 'Tôi có thể trở thành giảng viên trên EduStart không?',
      a: 'Có. Hãy xem mục Trở thành giảng viên để biết thêm và bắt đầu đăng ký hướng dẫn.',
    },
  ],
};

export const ABOUT = {
  TITLE: 'Về chúng tôi',
  CRUMB: 'Giới thiệu',
  KICKER: 'Về chúng tôi',
  H2: 'Chào mừng đến EduStart',
  P1:
    'Tại EduStart, chúng tôi tin vào trải nghiệm học tập dễ tiếp cận và sáng tạo, phù hợp lịch trình và phong cách của bạn. Hãy cùng chúng tôi đón nhận tương lai giáo dục và phát huy tiềm năng với các khóa học trực tuyến sâu sắc.',
  P2:
    'Chào mừng đến EduStart, nơi học tập không có ranh giới. Sứ mệnh của chúng tôi là trao quyền cho mọi người trên thế giới thông qua giáo dục dễ tiếp cận và đổi mới. Điều làm nên sự khác biệt:',
  VISION: 'Tầm nhìn',
  P_VISION:
    'EduStart hình dung một thế giới nơi ai cũng có thể học, bất kể địa điểm hay hoàn cảnh. Chúng tôi phá vỡ rào cản để giáo dục trở nên chuyển hóa và bao trừm.',
  EXCELLENCE: 'Cam kết chất lượng',
  P_EXCELLENCE:
    'Chúng tôi tập trung vào giáo dục đạt chuẩn cao. Đội ngũ phối hợp chuyên gia ngành và nhà giáo để xây dựng khóa học cập nhật, mang lại giá trị thực cho người học.',
  EMPOWER: 'Trao quyền cho người học',
  P_EMPOWER:
    'Giáo dục có sức thay đổi. EduStart giúp mọi người theo đuổi đam mê, thăng tiến sự nghiệp và học kỹ năng mới trong môi trường năng động, hỗ trợ.',
  INNOVATION: 'Đổi mới trong học tập',
  P_INNOVATION:
    'Ứng dụng công nghệ, chúng tôi mang đến phương pháp và công cụ học tập mới. Từ học phần tương tác đến buổi trực tiếp, chúng tôi tạo trải nghiệm hấp dẫn và giúp ghi nhớ kiến thức.',
  COMMUNITY: 'Hướng đến cộng đồng',
  P_COMMUNITY:
    'EduStart không chỉ là khóa học mà còn là cộng đồng sôi động. Chúng tôi khuyến khích hợp tác, thảo luận và chia sẻ kiến thức.',
  DIVERSE: 'Giáo dục đa dạng và hòa nhập',
  P_DIVERSE:
    'Chúng tôi trân trọng đa dạng quan điểm, văn hóa và ý tưởng. Danh mục khóa học phong phú phù hợp nhiều sở thích và trình độ.',
  IMPROVE: 'Cải tiến liên tục',
  P_IMPROVE:
    'Chúng tôi không ngừng phát triển. Phản hồi từ học viên giúp nâng cấp nền tảng, linh hoạt và sát nhu cầu người dùng.',
  CLOSING:
    'Cảm ơn bạn đã là một phần của EduStart. Cùng nhau, hãy bước trên hành trình học tập suốt đời.',
  VALUES_TITLE: 'Giá trị cốt lõi',
  VALUES_LEAD:
    'Những định hướng giúp EduStart đồng hành cùng bạn trên hành trình học tập.',
  CTA_JOIN: 'Tham gia EduStart',
};

export const COURSES_PAGE = {
  TITLE: 'Khóa học',
  CRUMB: 'Khóa học',
  CATEGORIES: 'Danh mục',
  TOPICS: 'Chủ đề phổ biến',
  ALL_COURSES: 'Tất cả khóa học',
  EMPTY: 'Chưa có khóa học được xuất bản. Hãy seed cơ sở dữ liệu hoặc thêm từ quản trị.',
  VIEW_COURSE_ARIA: 'Xem chi tiết khóa học',
  OPEN_COURSE: 'Xem khóa học',
};

export const CLASSES_PAGE = {
  TITLE: 'Lớp học',
  CRUMB: 'Lớp học',
  ALL: 'Các lớp đang mở',
  SUB: 'Chọn lớp để xem mô tả và tham gia học tập cùng giảng viên.',
  EMPTY: 'Chưa có lớp nào đang mở. Hãy thử lại sau hoặc liên hệ hỗ trợ.',
  VIEW_CLASS_ARIA: 'Xem chi tiết lớp',
  OPEN_CLASS: 'Xem lớp',
};

/** Badge trên thẻ danh mục khi học viên đã đăng ký / chờ duyệt (chỉ hiện khi đã đăng nhập học viên). */
export const CATALOG_BADGES = {
  COURSE_ENROLLED: 'Đã đăng ký',
  CLASS_JOINED: 'Đã tham gia',
  PENDING: 'Chờ xác nhận',
};

/** Chọn phương thức thanh toán khi đăng ký khóa / lớp (xác nhận thủ công bởi admin). */
export const PAYMENT = {
  DIALOG_TITLE: 'Chọn phương thức thanh toán',
  NOTE_LABEL: 'Ghi chú (mã GD, nội dung chuyển khoản…)',
  NOTE_HELPER: 'Giúp quản trị đối soát nhanh hơn.',
  CONFIRM: 'Xác nhận',
  METHOD_CASH: 'Tiền mặt',
  METHOD_BANK: 'Chuyển khoản ngân hàng',
  METHOD_MOMO: 'Ví MoMo',
  METHOD_VNPAY: 'VNPAY',
  PENDING_MSG: 'Đã gửi yêu cầu. Vui lòng hoàn tất thanh toán (nếu cần) và chờ quản trị viên xác nhận.',
  REJECTED_HINT: 'Yêu cầu trước đó chưa được chấp nhận. Bạn có thể chọn phương thức và gửi lại.',
  ALREADY_PENDING: 'Bạn đã có yêu cầu đang chờ duyệt.',
  PENDING_COURSE_LOCK:
    'Bạn đã đăng ký và đang chờ xác nhận thanh toán. Nội dung khóa học sẽ mở sau khi được duyệt.',
  PENDING_CLASS_LOCK:
    'Bạn đã gửi tham gia lớp và đang chờ xác nhận thanh toán. Nội dung lớp sẽ mở sau khi được duyệt.',
};

export const CLASS_DETAIL = {
  TITLE_FALLBACK: 'Lớp học',
  CRUMB: 'Lớp học',
  BACK: 'Quay lại danh sách lớp',
  NO_DESC: 'Chưa có mô tả.',
  ENROLL: 'Tham gia lớp',
  ENROLLING: 'Đang tham gia…',
  ENROLL_SUCCESS: 'Tham gia lớp thành công!',
  TEACHER: 'Giảng viên',
  SCHEDULE: 'Lịch',
  STARTS: 'Bắt đầu',
  ENDS: 'Kết thúc',
  STUDENTS: 'Học viên',
  LOGIN_STUDENT: 'Vui lòng đăng nhập với tư cách học viên để tham gia lớp.',
  ONLY_STUDENT: 'Chỉ học viên mới có thể thực hiện thao tác này.',
  DIALOG_AUTH_TITLE: 'Cần đăng nhập hoặc đăng ký',
  DIALOG_AUTH_BODY: 'Vui lòng đăng nhập hoặc tạo tài khoản học viên để tham gia lớp này.',
  DIALOG_LOGIN: 'Đăng nhập',
  DIALOG_SIGNUP: 'Đăng ký tài khoản',
  DIALOG_ROLE_TITLE: 'Không thể tham gia',
  GO_DASHBOARD: 'Bảng học viên',
  GO_STUDY: 'Vào học',
  SECTION_LECTURES: 'Bài giảng',
  LECTURES_SUBTITLE: 'Các bài theo thứ tự. Mở từng bài khi bạn đã tham gia lớp.',
  SECTION_QUIZZES: 'Bài kiểm tra',
  QUIZZES_SUBTITLE: 'Làm bài theo thứ tự.',
  QUIZ_Q_COUNT: '{n} câu hỏi',
  NO_LECTURES: 'Chưa có bài giảng nào.',
  NO_QUIZZES: 'Chưa có bài kiểm tra nào.',
  SUBMIT_QUIZ: 'Làm bài',
  LOCKED_HINT: 'Bài giảng chỉ dành cho học viên đã tham gia lớp. Hãy tham gia lớp để xem nội dung.',
  LOCKED_QUIZZES: 'Bài kiểm tra chỉ khả dụng sau khi bạn đã tham gia lớp.',
  LOCKED_SCHEDULE: 'Lịch học chi tiết chỉ hiển thị sau khi bạn tham gia lớp.',
  SCHEDULES_TITLE: 'Lịch học',
  SCHEDULE_TBA: 'Sắp xếp',
};

export const COURSE_DETAIL = {
  TITLE_FALLBACK: 'Khóa học',
  CRUMB: 'Khóa học',
  BACK: 'Quay lại danh sách khóa học',
  NO_DESC: 'Chưa có mô tả.',
  LEVEL: 'Cấp độ',
  DURATION: 'Thời lượng',
  ENROLL: 'Đăng ký ngay',
  ENROLLING: 'Đang đăng ký…',
  ENROLL_SUCCESS: 'Đăng ký thành công!',
  LOGIN_STUDENT: 'Vui lòng đăng nhập với tư cách học viên để đăng ký.',
  ONLY_STUDENT: 'Chỉ học viên mới có thể thực hiện thao tác này.',
  LOGIN_LINK: 'Đăng nhập',
  LOGIN_SUFFIX: ' với tư cách học viên để đăng ký.',
  SECTION_LECTURES: 'Bài giảng',
  LECTURES_SUBTITLE: 'Danh sách bài theo thứ tự. Bấm vào từng bài để xem trang chi tiết.',
  LECTURE_PARTS: '{n} phần nội dung',
  SECTION_QUIZZES: 'Bài kiểm tra',
  QUIZZES_SUBTITLE: 'Danh sách bài theo thứ tự. Mở từng bài để làm và nộp bài.',
  QUIZ_Q_COUNT: '{n} câu hỏi',
  NO_LECTURES: 'Chưa có bài giảng nào.',
  NO_QUIZZES: 'Chưa có bài kiểm tra nào.',
  SUBMIT_QUIZ: 'Nộp bài',
  SUBMITTING_QUIZ: 'Đang chấm…',
  QUIZ_SCORE: 'Đúng {correct}/{total} câu ({percent}%).',
  QUIZ_SUBMIT_ERR: 'Không nộp bài được. Vui lòng thử lại.',
  OPEN_VIDEO: 'Mở video',
  LOCKED_HINT:
    'Nội dung bài giảng chỉ dành cho học viên đã đăng ký. Hãy đăng ký khóa học để xem và học.',
  LOCKED_QUIZZES: 'Bài kiểm tra chỉ khả dụng sau khi bạn đã đăng ký khóa học.',
  DIALOG_AUTH_TITLE: 'Cần đăng nhập hoặc đăng ký',
  DIALOG_AUTH_BODY:
    'Vui lòng đăng nhập hoặc tạo tài khoản học viên để đăng ký và học khóa học này.',
  DIALOG_LOGIN: 'Đăng nhập',
  DIALOG_SIGNUP: 'Đăng ký tài khoản',
  DIALOG_ROLE_TITLE: 'Không thể đăng ký',
  GO_DASHBOARD: 'Bảng học viên',
  GO_STUDY: 'Vào học',
  RATING: 'Điểm trung bình',
  ENROLLMENT_LABEL: 'Học viên đã đăng ký',
  REVIEW_VOTES: 'lượt đánh giá',
  SECTION_REVIEWS: 'Đánh giá từ học viên',
  REVIEWS_LEAD: 'Mọi đánh giá đều từ học viên đã đăng ký.',
  NO_REVIEWS: 'Chưa có đánh giá nào. Hãy là người đầu tiên sau khi đăng ký.',
  YOUR_REVIEW: 'Đánh giá của bạn',
  STARS: 'Số sao',
  COMMENT: 'Nhận xét (tuỳ chọn)',
  SUBMIT_REVIEW: 'Gửi đánh giá',
  SAVING_REVIEW: 'Đang lưu…',
  REVIEW_SAVED: 'Đã lưu đánh giá.',
  REVIEW_ERR: 'Không lưu được. Vui lòng thử lại.',
  REVIEW_MUST_ENROLL: 'Chỉ học viên đã đăng ký mới có thể gửi đánh giá.',
  REVIEW_GUEST: 'Đăng ký khóa học để chia sẻ trải nghiệm.',
};

export const QUIZ_DETAIL = {
  NOT_FOUND: 'Không tìm thấy bài kiểm tra này.',
  QUIZ_PROGRESS: 'Bài kiểm tra {current} / {total}',
};

export const LECTURE_DETAIL = {
  BACK_TO_COURSE: 'Về khóa học',
  NOT_FOUND: 'Không tìm thấy bài giảng này.',
  PREV: 'Bài trước',
  NEXT: 'Bài sau',
  LECTURE_PROGRESS: 'Bài {current} / {total}',
  PART_LABEL: 'Phần {n}',
  VIDEO_HEADING: 'Video',
  CONTENT_HEADING: 'Nội dung',
};

export const CONTACT_PAGE = {
  TITLE: 'Liên hệ',
  CRUMB: 'Liên hệ',
  H2: 'Liên hệ với chúng tôi',
  H3: 'Kết nối',
  INTRO:
    'Chúng tôi sẵn sàng hỗ trợ câu hỏi về khóa học EduStart, hợp tác hay hỗ trợ kỹ thuật.',
  OFFICE: 'Văn phòng',
  OFFICE_ADDR: SITE_CONTACT.ADDRESS,
  MOBILE: 'Di động',
  YOUR_NAME: 'Họ tên',
  SUBJECT: 'Tiêu đề',
  MESSAGE: 'Nội dung',
  SENT_OK: 'Đã gửi tin nhắn. Chúng tôi sẽ phản hồi sớm.',
  SENDING: 'Đang gửi…',
  SEND: 'Gửi tin nhắn',
};

export const TEAM_PAGE = {
  TITLE: 'Đội ngũ',
  CRUMB: 'Đội ngũ',
  KICKER: 'Đội ngũ',
  H2: 'Gặp gỡ giảng viên',
  EMPTY: 'Chưa có thành viên. Thêm từ bảng quản trị.',
};

export const TESTI_PAGE = {
  TITLE: 'Đánh giá',
  CRUMB: 'Đánh giá',
  KICKER: 'Đánh giá',
  H2: 'Học viên nói gì',
  EMPTY: 'Chưa có đánh giá. Gửi từ form bên dưới hoặc thêm từ bảng quản trị (tab Đội ngũ & đánh giá → Đánh giá).',
  FORM_KICKER: 'Góp ý',
  FORM_TITLE: 'Gửi đánh giá của bạn',
  FORM_LEAD:
    'Bạn đã trải nghiệm EduStart? Hãy chia sẻ cảm nhận — gửi ở đây sẽ lưu vào danh sách đánh giá công khai. Email bạn nhập dùng để liên hệ, không hiển thị trên thẻ; trang “Liên hệ” dùng form riêng (lưu ở Tin liên hệ, không vào bảng đánh giá).',
  FORM_SENT: 'Cảm ơn bạn! Đánh giá đã được ghi nhận.',
  FORM_ERR: 'Không gửi được. Vui lòng thử lại.',
  FORM_RATING: 'Mức hài lòng (sao)',
  FORM_ROLE: 'Vai trò (tuỳ chọn)',
  FORM_CONTENT: 'Nội dung đánh giá',
  FORM_SUBMIT: 'Gửi đánh giá',
  FORM_PLACEHOLDER: 'Chia sẻ trải nghiệm học tập, gợi ý cải thiện…',
  FORM_REQUIRED: 'Vui lòng nhập họ tên, email và nội dung đánh giá.',
};


export const INSTRUCTOR_PAGE = {
  TITLE: 'Hợp tác đào tạo',
  CRUMB: 'Hợp tác',
  H2: 'Chia sẻ kiến thức cùng EduStart',
  H3: 'Chào mừng đến EduStart',
  P1:
    'Bạn đam mê chia sẻ chuyên môn và tạo tác động cho học viên khắp nơi? Hãy gia nhập cộng đồng nhà giáo vì sự yêu thích học tập.',
  P2:
    'Bắt đầu bằng cách tạo tài khoản học viên. Nội dung và khóa học do quản trị viên quản lý; liên hệ đội ngũ nếu bạn muốn đồng hành giảng dạy.',
  CTA: 'Tạo tài khoản',
  WHY: 'Vì sao giảng dạy cùng chúng tôi?',
  WHY_P:
    'Tiếp cận học viên toàn cầu và đồng hành cùng quản trị để xây nội dung chất lượng trên nền tảng của chúng tôi.',
};

export const AUTH = {
  LOGIN_TITLE: 'Đăng nhập',
  LOGIN_CRUMB: 'Đăng nhập',
  LOGIN_LEAD: 'Nhập email và mật khẩu để vào bảng điều khiển và tiếp tục học.',
  SIGNUP_TITLE: 'Đăng ký',
  SIGNUP_CRUMB: 'Đăng ký',
  SIGNUP_LEAD: 'Tạo tài khoản học viên để đăng ký khóa học và theo dõi tiến độ.',
  PASSWORD_HINT: 'Tối thiểu 6 ký tự.',
  CREATE_ACCOUNT: 'Tạo tài khoản',
  FULL_NAME: 'Họ và tên',
  NO_ACCOUNT: 'Chưa có tài khoản?',
  HAS_ACCOUNT: 'Đã có tài khoản?',
  CHECK_EMAIL: 'Kiểm tra email để xác nhận tài khoản, sau đó đăng nhập.',
  LOGIN_SUCCESS: 'Đăng nhập thành công.',
  SIGNUP_SUCCESS: 'Đăng ký thành công.',
};

export const DASH_STUDENT = {
  TITLE: 'Bảng học viên',
  GREETING: 'Xin chào, {name}',
  GREETING_FALLBACK: 'Xin chào',
  LEAD: 'Theo dõi khóa học, bài giảng và bài kiểm tra tại một nơi.',
  MY_COURSES: 'Khóa học của tôi',
  TH_COURSE: 'Khóa học',
  TH_ENROLLED: 'Ngày đăng ký',
  EMPTY: 'Bạn chưa đăng ký khóa học nào.',
  GO_STUDY: 'Vào học',
  STAT_COURSES: 'Khóa đã đăng ký',
  STAT_LECTURES: 'Bài giảng',
  STAT_QUIZZES: 'Bài kiểm tra',
  STAT_QUIZ_ATTEMPTS: 'Lượt làm bài',
  STAT_QUIZ_AVG: 'Điểm TB (%)',
  QUIZ_LAST_SCORE: 'Lần làm gần nhất',
  QUIZ_SCORE_SHORT: '{correct}/{total} — {percent}%',
  SECTION_QUIZ_HISTORY: 'Lịch sử làm bài',
  SECTION_QUIZ_HISTORY_SUB: 'Các lượt nộp gần đây.',
  TH_QUIZ_NAME: 'Bài kiểm tra',
  TH_QUIZ_SCORE: 'Điểm',
  TH_QUIZ_DATE: 'Thời gian',
  EMPTY_QUIZ_HISTORY: 'Chưa có lượt làm bài nào.',
  SECTION_LECTURES: 'Bài giảng của tôi',
  SECTION_LECTURES_SUB: 'Nội dung trong các khóa bạn đã đăng ký.',
  SECTION_QUIZZES: 'Bài kiểm tra của tôi',
  SECTION_QUIZZES_SUB: 'Luyện tập và nộp bài trên từng khóa.',
  EMPTY_LEARN_HINT: 'Đăng ký khóa học để xem bài giảng và bài kiểm tra tại đây.',
  EMPTY_LECTURES: 'Chưa có bài giảng trong các khóa của bạn.',
  EMPTY_QUIZZES: 'Chưa có bài kiểm tra trong các khóa của bạn.',
  LINK_LECTURES: 'Mở phần bài giảng',
  LINK_QUIZZES: 'Mở phần bài kiểm tra',
  LOADING_LEARN: 'Đang tải nội dung khóa học…',
  ENROLLED_ON: 'Đăng ký:',
  SECTION_LEARN_BY_COURSE: 'Nội dung theo từng khóa',
  SECTION_LEARN_BY_COURSE_SUB: 'Bài giảng và bài kiểm tra trong các khóa bạn đã đăng ký — mở từng khóa để xem chi tiết.',
  EMPTY_COURSE_CONTENT: 'Khóa này chưa có bài giảng hay bài kiểm tra.',
  CTA_BROWSE_COURSES: 'Khám phá khóa học',
  CTA_BROWSE_COURSES_HINT: 'Xem danh mục để chọn và đăng ký khóa phù hợp.',
  LOAD_ENROLLMENTS_ERROR: 'Không tải được danh sách đăng ký. Bạn có thể tải lại trang hoặc thử lại sau.',
  SUBHEAD_QUIZZES: 'Trắc nghiệm',
  SUBHEAD_LECTURES: 'Bài giảng',
  CHIP_LECTURES: '{n} bài giảng',
  CHIP_QUIZZES: '{n} bài kiểm tra',
  EMPTY_LEARN_ALL: 'Các khóa bạn đăng ký chưa có bài giảng hay bài kiểm tra.',
  MY_CLASSES: 'Lớp được phân',
  SECTION_MY_CLASSES: 'Lớp học trực tiếp',
  SECTION_MY_CLASSES_SUB: 'Bài giảng, bài kiểm tra và lịch học do giáo viên quản lý.',
  EMPTY_CLASSES: 'Bạn chưa được phân vào lớp nào.',
  CTA_BROWSE_CLASSES: 'Xem lớp đang mở',
  CTA_BROWSE_CLASSES_HINT: 'Tham gia lớp phù hợp để học cùng giảng viên.',
  TH_CLASS_NAME: 'Lớp',
  CLASS_LINK_LEARN: 'Vào lớp',
  LOAD_CLASSES_ERROR: 'Không tải được danh sách lớp.',
  STATS_SECTION: 'Thống kê học tập',
  STATS_SECTION_SUB: 'Tổng quan khóa học, lớp và kết quả làm bài của bạn.',
  STAT_MY_CLASSES: 'Lớp đang học',
  CHART_ATTEMPTS_BY_SOURCE: 'Lượt làm bài theo khóa / lớp',
  CHART_ATTEMPTS_30D: 'Lượt làm bài 30 ngày gần đây',
  CHART_LEGEND_ATTEMPT_COUNT: 'Số lượt',
};

export const DASH_ADMIN = {
  TITLE: 'Bảng quản trị',
  CRUMB: 'Quản trị',
  LEAD_USERS: 'Thêm, sửa và gán vai trò tài khoản trên nền tảng.',
  USER_STATS_SECTION: 'Thống kê người dùng',
  USER_STATS_TOTAL: 'Tổng tài khoản',
  USER_STATS_STUDENT_COUNT: 'Học viên',
  USER_STATS_ADMIN_COUNT: 'Quản trị',
  USER_STATS_TEACHER_COUNT: 'Giáo viên',
  USER_CHART_BY_ROLE: 'Phân bố theo vai trò',
  USER_CHART_SIGNUPS_30D: 'Tài khoản mới 30 ngày gần đây',
  USER_CHART_LEGEND_COUNT: 'Số người dùng',
  USER_CHART_LEGEND_NEW_PER_DAY: 'Tài khoản mới trong ngày',
  LEAD_COURSES: 'Tạo khóa học, quản lý danh sách và biên soạn bài giảng, bài kiểm tra.',
  LEAD_ENROLLMENTS: 'Theo dõi học viên đã đăng ký theo khóa và theo thời gian.',
  LEAD_QUIZ_ANALYTICS: 'Tổng hợp lượt làm bài, điểm trung bình và phân bố kết quả.',
  SECTION_ADD_COURSE: 'Tạo khóa học mới',
  SECTION_COURSE_LIST: 'Danh sách khóa học',
  COURSE_VIEW_CATALOG: 'Danh mục',
  COURSE_VIEW_CONTENT: 'Nội dung',
  FORM_ADD_LECTURE: 'Form thêm bài giảng',
  FORM_ADD_QUIZ: 'Form thêm bài kiểm tra',
  COURSE_STATS_SECTION: 'Thống kê khóa học và nội dung',
  COURSE_STATS_TOTAL_COURSES: 'Tổng khóa học',
  COURSE_STATS_PUBLISHED_COUNT: 'Đã xuất bản',
  COURSE_STATS_LECTURES: 'Tổng bài giảng',
  COURSE_STATS_QUIZZES: 'Tổng trắc nghiệm',
  COURSE_CHART_PUBLISH: 'Trạng thái xuất bản',
  COURSE_CHART_TOP_CONTENT: 'Nội dung theo khóa học',
  COURSE_CHART_ACTIVITY_30D: 'Tạo mới 30 ngày (khóa / bài giảng / trắc nghiệm)',
  COURSE_CHART_LINE_NEW_COURSES: 'Khóa học mới',
  COURSE_CHART_LINE_NEW_LECTURES: 'Bài giảng mới',
  COURSE_CHART_LINE_NEW_QUIZZES: 'Trắc nghiệm mới',
  STATUS_PUBLISHED: 'Đã xuất bản',
  STATUS_DRAFT: 'Nháp',
  DELETE_TOOLTIP: 'Xóa',
  COURSE_CREATED: 'Đã tạo khóa học',
  COURSE_UPDATED: 'Đã cập nhật khóa học',
  COURSE_DIALOG_EDIT: 'Sửa khóa học',
  EDIT_TOOLTIP: 'Sửa',
  TITLE_REQUIRED: 'Vui lòng nhập tiêu đề khóa học.',
  CONFIRM_DEL_CAT: 'Xóa danh mục này?',
  CONFIRM_DEL_COURSE: 'Xóa khóa học này?',
  CONFIRM_DEL: 'Xóa mục này?',
  TABS: {
    users: 'Người dùng',
    classes: 'Lớp học',
    courses: 'Khóa học',
    payments: 'Thanh toán',
    enrollments: 'Đăng ký khóa học',
    quiz_stats: 'Bài kiểm tra',
    content: 'Đội ngũ & đánh giá',
  },
  PAYMENTS_LEAD: 'Phê duyệt thanh toán đăng ký khóa học và tham gia lớp.',
  PAYMENTS_SUB_COURSES: 'Khóa học',
  PAYMENTS_SUB_CLASSES: 'Lớp học',
  PAYMENTS_FILTER_STATUS: 'Trạng thái',
  PAYMENTS_STATUS_PENDING: 'Chờ duyệt',
  PAYMENTS_STATUS_APPROVED: 'Đã duyệt',
  PAYMENTS_STATUS_REJECTED: 'Từ chối',
  PAYMENTS_STATUS_ALL: 'Tất cả',
  PAYMENTS_TH_STUDENT: 'Học viên',
  PAYMENTS_TH_EMAIL: 'Email',
  PAYMENTS_TH_TARGET: 'Khóa / lớp',
  PAYMENTS_TH_METHOD: 'Phương thức',
  PAYMENTS_TH_AMOUNT: 'Giá',
  PAYMENTS_TH_DATE: 'Ngày gửi',
  PAYMENTS_TH_STATUS: 'Trạng thái',
  PAYMENTS_TH_NOTE: 'Ghi chú',
  PAYMENTS_TH_ACTIONS: 'Thao tác',
  PAYMENTS_APPROVE: 'Duyệt',
  PAYMENTS_REJECT: 'Từ chối',
  PAYMENTS_EMPTY: 'Không có bản ghi.',
  PAYMENTS_STATS_SECTION: 'Thống kê thanh toán',
  PAYMENTS_CHART_BY_STATUS: 'Theo trạng thái',
  PAYMENTS_CHART_BY_METHOD: 'Theo phương thức thanh toán',
  PAYMENTS_CHART_BY_DAY: 'Bản ghi theo ngày (30 ngày)',
  PAYMENTS_CHART_LEGEND_RECORDS: 'Số bản ghi',
  PAYMENTS_CHART_CAPTION: 'Tổng {n} bản ghi thanh toán',
  PAYMENTS_METHOD_UNSET: 'Không khai báo / khác',
  PAYMENTS_PRICE_NONE: '—',
  PAYMENTS_TOAST_UPDATED: 'Đã cập nhật trạng thái thanh toán.',
  /** Mục con trong tab Khóa học (đăng ký & bài kiểm tra nằm dưới đây). */
  COURSE_AREA_OVERVIEW: 'Khóa học & nội dung',
  TABLE_PAGINATION_LABEL_ROWS: 'Dòng mỗi trang',
  CMS_INTRO: 'Nội dung công khai và hộp thư người dùng.',
  CMS_SUBTAB_TEAM: 'Đội ngũ',
  CMS_SUBTAB_TESTI: 'Đánh giá',
  CMS_SUBTAB_CONTACT: 'Tin liên hệ',
  CMS_TEAM_STATS_SECTION: 'Thống kê đội ngũ',
  CMS_TEAM_TOTAL: 'Tổng thành viên',
  CMS_TEAM_ROLE_KINDS: 'Số loại chức danh',
  CMS_TEAM_NEW_30D: 'Thêm mới 30 ngày',
  CMS_TEAM_CHART_ROLES: 'Theo chức danh',
  CMS_TEAM_CHART_TIMELINE: 'Thành viên mới 30 ngày gần đây',
  CMS_ROLE_UNLABELED: 'Chưa gán chức danh',
  CMS_TESTI_STATS_SECTION: 'Thống kê đánh giá',
  CMS_TESTI_TOTAL: 'Tổng bản ghi',
  CMS_TESTI_RATED_COUNT: 'Có chấm sao',
  CMS_TESTI_AVG_STARS: 'Trung bình sao',
  CMS_TESTI_CHART_RATING: 'Phân bố số sao',
  CMS_TESTI_CHART_TIMELINE: 'Đánh giá mới 30 ngày gần đây',
  CMS_TESTI_STAR_N: '{n} sao',
  CMS_CHART_COUNT: 'Số lượng',
  CMS_LINE_NEW_PER_DAY: 'Mới theo ngày',
  CMS_CONTACT_INTRO:
    'Chỉ liệt kê tin gửi từ trang Liên hệ. Đánh giá công khai do khách gửi từ trang Đánh giá nằm ở tab Đánh giá, không hiển thị ở đây.',
  CMS_CONTACT_EMPTY: 'Chưa có tin nhắn nào.',
  CMS_CONTACT_STATS_SECTION: 'Thống kê tin liên hệ',
  CMS_CONTACT_TOTAL: 'Tổng tin (tải gần nhất)',
  CMS_CONTACT_HAS_SUBJECT: 'Có tiêu đề',
  CMS_CONTACT_NO_SUBJECT_LABEL: 'Không tiêu đề',
  CMS_CONTACT_CHART_SUBJECT: 'Phân loại tiêu đề',
  CMS_CONTACT_CHART_TIMELINE: 'Tin nhận 30 ngày gần đây',
  CMS_CONTACT_DETAIL: 'Chi tiết tin nhắn',
  CMS_CONFIRM_DEL_CONTACT: 'Xóa tin liên hệ này?',
  TH_MSG_PREVIEW: 'Nội dung (rút gọn)',
  CMS_COL_NAME: 'Tên',
  CMS_COL_ROLE: 'Vai trò',
  CMS_COL_BIO: 'Giới thiệu',
  CMS_COL_SRC: 'Nội dung / Ảnh',
  CMS_COL_RATING: 'Sao',
  CMS_ADD_TEAM: 'Thành viên mới',
  CMS_ADD_TESTI: 'Đánh giá mới',
  CMS_EDIT_TEAM: 'Sửa thành viên',
  CMS_EDIT_TESTI: 'Sửa đánh giá',
  CMS_TH_ORDER: 'Thứ tự',
  CMS_CONFIRM_DEL_TEAM: 'Xóa thành viên này?',
  CMS_CONFIRM_DEL_TESTI: 'Xóa đánh giá này?',
  CMS_TOAST_UPDATED: 'Đã cập nhật',
  CMS_ERR_TEAM_NAME: 'Vui lòng nhập tên thành viên.',
  CMS_ERR_TESTI_FIELDS: 'Vui lòng nhập tên tác giả và nội dung.',
  ENROLL_STATS_TITLE: 'Học viên theo khóa học',
  ENROLL_TIMELINE_TITLE: 'Đăng ký 30 ngày gần đây',
  ENROLL_FILTER_ALL: 'Tất cả khóa học',
  TH_ENROLL_COURSE: 'Khóa học',
  TH_ENROLL_STUDENT: 'Học viên',
  TH_ENROLL_EMAIL: 'Email',
  TH_ENROLL_DATE: 'Ngày đăng ký',
  CHART_STUDENTS: 'Số học viên',
  ENROLL_TABLE_EMPTY: 'Chưa có đăng ký nào.',
  QUIZ_ANALYTICS_SUMMARY_ATTEMPTS: 'Tổng lượt làm',
  QUIZ_ANALYTICS_SUMMARY_AVG: 'Điểm TB',
  QUIZ_ANALYTICS_SUMMARY_STUDENTS: 'Học viên tham gia',
  QUIZ_ANALYTICS_CHART_COURSE: 'Lượt làm theo khóa',
  QUIZ_ANALYTICS_CHART_TIMELINE: 'Lượt làm 30 ngày gần đây',
  QUIZ_ANALYTICS_CHART_SCORE: 'Phân bố điểm (%)',
  QUIZ_ANALYTICS_TABLE_TITLE: 'Chi tiết lượt làm',
  QUIZ_ANALYTICS_EMPTY: 'Chưa có dữ liệu bài kiểm tra.',
  CHART_ATTEMPTS: 'Lượt',
  CHART_AVG_SUFFIX: 'TB %',
  QUIZ_ANAL_TH_SCORE: 'Kết quả',
  COURSE_CONTENT: 'Nội dung khóa học',
  PICK_COURSE: 'Chọn khóa học',
  SUBTAB_LECTURES: 'Bài giảng',
  SUBTAB_QUIZZES: 'Bài kiểm tra',
  LECTURE_TITLE: 'Tiêu đề bài giảng',
  LECTURE_CONTENT: 'Nội dung (tùy chọn)',
  LECTURE_VIDEO: 'URL video (tùy chọn)',
  ADD_LECTURE: 'Thêm bài giảng',
  LECTURE_BLOCKS: 'Khối bài học',
  LECTURE_BLOCK_TITLE: 'Tiêu đề khối (tùy chọn)',
  LECTURE_BLOCK_CONTENT: 'Nội dung',
  LECTURE_BLOCK_VIDEO: 'URL video',
  ADD_LECTURE_BLOCK: 'Thêm khối',
  REMOVE_LECTURE_BLOCK: 'Xóa khối',
  LECTURE_BLOCKS_EMPTY: 'Thêm ít nhất một khối có tiêu đề, nội dung hoặc video.',
  LECTURE_TITLE_REQUIRED: 'Vui lòng nhập tiêu đề bài giảng.',
  LECTURE_DIALOG_ADD: 'Thêm bài giảng',
  LECTURE_DIALOG_EDIT: 'Sửa bài giảng',
  QUIZ_DIALOG_ADD: 'Thêm bài kiểm tra',
  QUIZ_DIALOG_EDIT: 'Sửa bài kiểm tra',
  QUIZ_COL_QUESTIONS: 'Số câu',
  TH_LECTURE_BLOCKS: 'Số khối',
  QUIZ_TITLE: 'Tiêu đề bài kiểm tra',
  QUIZ_DESC: 'Mô tả',
  QUIZ_QUESTIONS_SECTION: 'Các câu hỏi',
  QUIZ_QUESTION_TEXT: 'Nội dung câu',
  QUIZ_OPTION_A: 'Đáp án A',
  QUIZ_OPTION_B: 'Đáp án B',
  QUIZ_OPTION_C: 'Đáp án C',
  QUIZ_OPTION_D: 'Đáp án D',
  QUIZ_CORRECT: 'Đáp án đúng',
  ADD_QUIZ_QUESTION: 'Thêm câu hỏi',
  REMOVE_QUIZ_QUESTION: 'Xóa câu',
  QUIZ_OPTIONS_REQUIRED: 'Mỗi câu cần đủ 4 đáp án A–D.',
  QUIZ_NEED_QUESTION: 'Thêm ít nhất một câu hỏi hợp lệ.',
  ADD_QUIZ: 'Thêm bài kiểm tra',
  TOAST_LECTURE_ADDED: 'Đã thêm bài giảng',
  TOAST_LECTURE_UPDATED: 'Đã cập nhật bài giảng',
  TOAST_QUIZ_ADDED: 'Đã thêm bài kiểm tra',
  TOAST_QUIZ_UPDATED: 'Đã cập nhật bài kiểm tra',
  CONFIRM_DEL_LECTURE: 'Xóa bài giảng này?',
  CONFIRM_DEL_QUIZ: 'Xóa bài kiểm tra này?',
  TH_LECTURE_TITLE: 'Bài giảng',
  TH_QUIZ_TITLE: 'Bài kiểm tra',
  TH_NAME: 'Tên',
  TH_ROLE: 'Vai trò',
  TH_ACTIONS: 'Thao tác',
  BTN_ADD_USER: 'Thêm người dùng',
  BTN_EDIT: 'Sửa',
  USER_DIALOG_CREATE: 'Thêm người dùng',
  USER_DIALOG_EDIT: 'Sửa người dùng',
  USER_CREATED: 'Đã tạo người dùng',
  USER_UPDATED: 'Đã cập nhật người dùng',
  CONFIRM_DEL_USER:
    'Xóa tài khoản này? Không thể hoàn tác.',
  CANNOT_DELETE_SELF: 'Không thể xóa chính tài khoản đang đăng nhập.',
  PASSWORD_REQUIRED: 'Vui lòng nhập mật khẩu.',
  EMAIL_REQUIRED: 'Vui lòng nhập email.',
  PW_LEAVE_BLANK: 'Để trống nếu không đổi mật khẩu',
  ROLE_STUDENT: 'Học viên',
  ROLE_ADMIN: 'Quản trị',
  ROLE_TEACHER: 'Giáo viên',
  TH_DATE: 'Ngày',
  TH_EMAIL: 'Email',
  TH_SUBJECT: 'Tiêu đề',
  TH_MESSAGE: 'Nội dung',
  PH_NAME: 'Tên',
  PH_SLUG: 'slug',
  PH_IMAGE_URL: 'URL ảnh',
  ADD_COURSE: 'Thêm khóa học',
  LABEL_COURSE_TITLE: 'Tiêu đề',
  LABEL_COURSE_DESC: 'Mô tả',
  LABEL_CATEGORY: 'Danh mục',
  LABEL_THUMB: 'URL ảnh đại diện',
  LABEL_PRICE_VND: 'Học phí (VNĐ)',
  PRICE_VND_HELPER: 'Nhập số nguyên (VNĐ). 0 = miễn phí.',
  TH_COURSE_TITLE: 'Tiêu đề',
  TH_COURSE_SLUG: 'Slug',
  TH_COURSE_PUBLISHED: 'Xuất bản',
  LABEL_PRICE_CENTS: 'Giá (xu / cents)',
  LABEL_DURATION_H: 'Thời lượng (giờ)',
  LABEL_LEVEL: 'Cấp độ',
  LABEL_PUBLISHED: 'Đã xuất bản',
  PH_ROLE: 'Chức danh',
  PH_BIO: 'Tiểu sử',
  PH_AUTHOR: 'Tác giả',
  PH_TITLE: 'Chức danh',
  PH_CONTENT: 'Nội dung',
  LEVEL_DEFAULT: 'Cơ bản',
  TOAST_CAT_ADDED: 'Đã thêm danh mục',
  TOAST_TEAM_ADDED: 'Đã thêm thành viên',
  TOAST_TEST_ADDED: 'Đã thêm đánh giá',
  TOAST_DELETED: 'Đã xóa',
  LEAD_CLASSES: 'Tạo lớp, phân giáo viên và quản lý danh sách học sinh.',
  CLASS_STATS_SECTION: 'Thống kê lớp học',
  CLASS_STATS_TOTAL: 'Tổng lớp',
  CLASS_STATS_ACTIVE_COUNT: 'Đang mở',
  CLASS_STATS_ARCHIVED_COUNT: 'Lưu trữ',
  CLASS_STATS_NEW_30D: 'Tạo mới 30 ngày',
  CLASS_CHART_BY_STATUS: 'Phân bố theo trạng thái',
  CLASS_CHART_NEW_30D: 'Lớp mới 30 ngày gần đây',
  CLASS_CHART_LEGEND_COUNT: 'Số lớp',
  CLASS_CHART_LEGEND_NEW_PER_DAY: 'Lớp mới trong ngày',
  SECTION_CLASS_LIST: 'Danh sách lớp học',
  BTN_ADD_CLASS: 'Tạo lớp',
  CLASS_DIALOG_CREATE: 'Tạo lớp học',
  CLASS_DIALOG_EDIT: 'Sửa lớp học',
  CLASS_NAME: 'Tên lớp',
  CLASS_SLUG_HINT: 'Để trống để hệ thống tạo slug từ tên.',
  CLASS_IMAGE_URL: 'URL ảnh bìa lớp',
  CLASS_IMAGE_HINT: 'Đường dẫn tĩnh (vd. /img/course-1.png) hoặc URL HTTPS. Để trống để dùng ảnh mặc định.',
  CLASS_TEACHER: 'Giáo viên phụ trách',
  CLASS_NAME_REQUIRED: 'Vui lòng nhập tên lớp.',
  CLASS_TEACHER_REQUIRED: 'Vui lòng chọn giáo viên phụ trách.',
  CLASS_STATUS: 'Trạng thái',
  CLASS_STATUS_ACTIVE: 'Đang mở',
  CLASS_STATUS_ARCHIVED: 'Lưu trữ',
  TH_CLASS_SLUG: 'Slug',
  TH_CLASS_TEACHER: 'Giáo viên',
  BTN_MANAGE_CLASS: 'Chi tiết',
  CLASS_STUDENTS_TITLE: 'Học sinh trong lớp',
  CLASS_ADD_STUDENT_EMAIL: 'Email học sinh',
  BTN_ADD_TO_CLASS: 'Thêm vào lớp',
  CLASS_STUDENT_ADDED: 'Đã thêm học sinh',
  CLASS_STUDENT_REMOVED: 'Đã xóa học sinh khỏi lớp',
  CLASS_CREATED: 'Đã tạo lớp',
  CLASS_UPDATED: 'Đã cập nhật lớp',
  CONFIRM_DEL_CLASS: 'Xóa lớp này và toàn bộ dữ liệu liên quan?',
  CLASS_DETAIL_TITLE: 'Chi tiết lớp (quản trị)',
  CLASS_MANAGE_SECTION_OVERLINE: 'Quản lý theo lớp: học sinh, giáo viên, bài giảng, bài kiểm tra, lịch',
  CLASS_DETAIL_SWITCH: 'Lớp đang quản lý',
  BTN_CLOSE_PANEL: 'Thu gọn',
  CLASS_TAB_STUDENTS: 'Học sinh',
  CLASS_TAB_TEACHER: 'Giáo viên',
  CLASS_TAB_SCHEDULE: 'Lịch học',
  CLASS_TEACHER_UPDATED: 'Đã cập nhật giáo viên phụ trách',
  CLASS_CONFIRM_DEL_SCHEDULE: 'Xóa buổi học này?',
  CLASS_SCHEDULE_DIALOG_ADD: 'Thêm buổi học',
  CLASS_SCHEDULE_DIALOG_EDIT: 'Sửa buổi học',
  CLASS_LECTURE_SORT: 'Thứ tự',
  CLASS_LECTURE_PUBLISHED: 'Hiển thị cho học sinh',
  USER_NOT_STUDENT: 'Người dùng không phải học viên.',
  USER_LOOKUP_NOT_FOUND: 'Không tìm thấy tài khoản với email này.',
};

export const DASH_TEACHER = {
  TITLE: 'Bảng giáo viên',
  CRUMB: 'Giáo viên',
  LEAD: 'Quản lý lớp được giao: học sinh, bài giảng, bài kiểm tra và lịch học.',
  SELECT_CLASS: 'Chọn lớp',
  TAB_OVERVIEW: 'Tổng quan',
  TAB_LECTURES: 'Bài giảng',
  TAB_QUIZZES: 'Bài kiểm tra',
  TAB_STUDENTS: 'Học sinh',
  TAB_SCHEDULE: 'Lịch học',
  TAB_ATTEMPTS: 'Kết quả kiểm tra',
  NO_CLASSES: 'Bạn chưa được phân lớp nào.',
  LOAD_ERROR: 'Không tải được dữ liệu lớp.',
  BTN_ADD_LECTURE: 'Thêm bài giảng',
  BTN_ADD_QUIZ: 'Thêm bài kiểm tra',
  BTN_ADD_SCHEDULE: 'Thêm buổi học',
  SCHEDULE_TITLE: 'Tiêu đề buổi học',
  SCHEDULE_START: 'Bắt đầu',
  SCHEDULE_END: 'Kết thúc',
  SCHEDULE_LOCATION: 'Địa điểm',
  SCHEDULE_URL: 'Link học trực tuyến',
  SCHEDULE_NOTES: 'Ghi chú',
  STUDENT_SEARCH: 'Tìm học sinh (email hoặc tên)',
  ROSTER_EMPTY: 'Chưa có học sinh trong lớp.',
  QUIZ_FORM_HINT: 'Dùng form thêm câu hỏi: 4 lựa chọn A–D và chọn đáp án đúng.',
  CLASS_COVER_URL: 'URL ảnh bìa lớp',
  CLASS_COVER_HINT: 'Ảnh hiển thị trên trang lớp và danh sách. Để trống dùng ảnh mặc định.',
  STATS_SECTION: 'Thống kê lớp giảng dạy',
  STATS_CLASSES: 'Số lớp',
  STATS_ENROLLMENTS: 'Ghi danh (tổng chỗ)',
  STATS_ENROLLMENTS_HINT: 'Mỗi học sinh trong mỗi lớp tính một chỗ; cùng một người ở hai lớp tính hai.',
  STATS_LECTURES: 'Bài giảng',
  STATS_QUIZZES: 'Bài kiểm tra',
  STATS_SCHEDULES: 'Buổi học',
  STATS_ATTEMPTS: 'Lượt làm bài',
  CHART_STUDENTS_BY_CLASS: 'Học sinh theo lớp',
  CHART_ATTEMPTS_30D: 'Lượt làm bài 30 ngày gần đây',
  CHART_LEGEND_STUDENTS: 'Số học sinh',
  CHART_LEGEND_ATTEMPTS: 'Lượt làm bài',
  STATS_LOAD_ERROR: 'Không tải được thống kê.',
};

export const CLASSROOM = {
  CRUMB: 'Lớp học',
  LECTURE_NOT_FOUND: 'Không tìm thấy bài giảng',
  QUIZ_NOT_FOUND: 'Không tìm thấy bài kiểm tra',
  LOCKED: 'Bạn không có quyền truy cập lớp này.',
  SUBMIT: 'Nộp bài',
  RESULT: 'Kết quả',
};
